export default {

	// Auth
	LOGIN_CHECK_PENDING: 'LOGIN_CHECK_PENDING',
	LOGIN_CHECK_RESOLVED: 'LOGIN_CHECK_RESOLVED',
	LOGIN_CHECK_REJECTED: 'LOGIN_CHECK_REJECTED',

	LOGIN_PENDING: 'LOGIN_PENDING',
	LOGIN_RESOLVED: 'LOGIN_RESOLVED',
	LOGIN_REJECTED: 'LOGIN_REJECTED',

	LOGOUT_PENDING: 'LOGOUT_PENDING',
	LOGOUT_RESOLVED: 'LOGOUT_RESOLVED',
	LOGOUT_REJECTED: 'LOGOUT_REJECTED',
}
